# Generated by Django 5.2.4 on 2025-07-16 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state_desc', models.TextField()),
                ('current_status', models.TextField()),
                ('therapy_start', models.DateField()),
                ('registration_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('entry_date', models.DateField()),
                ('source', models.CharField(max_length=200)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTM.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.SmallIntegerField()),
                ('frequency_days', models.SmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CTM.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CTM.patient')),
            ],
        ),
    ]
