# Generated by Django 5.2.4 on 2025-09-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAmounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('change_date', models.DateField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTM.medication')),
            ],
        ),
    ]
